### ISSUE TITLE
 I don't see my profile in Leaderboard

### ISSUE THREAD

**Issue by Mirovan** [myriadsocial/myriad-api#371]
I  have 12 Kudos, but I don't see my profile in Leaderboard (
Can you check me ?
0x6a9dd520b2c57c0d370304b12ef236525c13d321bf5dd169313f6c96ef0b436f

**Comment by irmannmal** [comment]
Hi @Mirovan, sorry our airdrop campaign held on this url https://app.testnet.myriad.social not on https://app.stg.myriad.systems
